<?php

namespace App\Entities;

use App\User;
use App\Entities\OrderItem;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;
class Order extends Model
{
    const REFUND_STATUS_PENDING = 'pending';
    const REFUND_STATUS_APPLIED = 'applied';
    const REFUND_STATUS_PROCESSING = 'processing';
    const REFUND_STATUS_SUCCESS = 'success';
    const REFUND_STATUS_FAILED = 'failed';

    const SHIP_STATUS_PENDING = 'pending';
    const SHIP_STATUS_DELIVERED = 'delivered';
    const SHIP_STATUS_RECEIVED = 'received';

    public static $refundStatusMap = [
        self::REFUND_STATUS_PENDING    => 'primary',
        self::REFUND_STATUS_APPLIED    => 'info',
        self::REFUND_STATUS_PROCESSING => 'warning',
        self::REFUND_STATUS_SUCCESS    => 'success',
        self::REFUND_STATUS_FAILED     => 'danger',
    ];

    public static $shipStatusMap = [
        self::SHIP_STATUS_PENDING   => 'primary',
        self::SHIP_STATUS_DELIVERED => 'danger',
        self::SHIP_STATUS_RECEIVED  => 'success',
    ];

    protected $guarded = [];

    protected $casts = [
        'closed'    => 'boolean',
        'reviewed'  => 'boolean',
        'address'   => 'json',
        'ship_data' => 'json',
        'extra'     => 'json',
    ];

    protected $dates = [
        'paid_at',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function($model){
           if(!$model->no){
               $model->no = static::findAvailableNo();
               if(!$model->no)return false;
           }
        });
    }

    public static function findAvailableNo(){
        $prefix = date('YmdHis');
        for($i = 0; $i < 10; $i++){
            $no = $prefix. str_pad(random_int(0, 999999), 6, '0', STR_PAD_LEFT);
            if(!static::where('no', $no)->exists()){
                return $no;
            }
        }
        \Log::warning('find order no failed');
        return false;
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function orderItems(){
        return $this->hasMany(OrderItem::class);
    }

}
